FROM node:22-alpine AS builder

WORKDIR /app

ARG SERVICE_PATH
COPY ${SERVICE_PATH}/package*.json ./
RUN npm ci

COPY ${SERVICE_PATH}/ ./
RUN npm run build

FROM node:22-alpine AS runner

WORKDIR /app

COPY --from=builder /app/package*.json ./
RUN npm ci --only=production

COPY --from=builder /app/dist ./dist

EXPOSE 5000-5010

CMD ["node", "dist/server.js"]
